[tasks.build]
command = "cargo"
args = [
    "build",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "--lib",
    "-Z",
    "build-std=std,panic_abort",
    "-Z",
    "build-std-features=panic_immediate_abort"
]
